os:
    - linux
    - osx
language: go
go:
    - 1.8.x
install:
- make dep
script: 
- make profile
- make coveralls
notifications:
    email:
    - dev@moistpetal.io
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/f501b9d7e4d9bc8a6fda
        on_success: change 
        on_failure: always
        on_start: never    
